### ISSUE TITLE
This is a complete implementation of the Scheme specification it?

### ISSUE THREAD

**Issue by insionng** [SteelSeries/golisp#9]

**Comment by dastels** [comment]
No. It is heavily inspired and influenced by Scheme (MIT/GNU scheme in particular). GoLisp 1.0 is much more in line with Scheme, but it is at it's heart a language for our purposes internally. It's growth and evolution reflect that.

GoLisp evolves along 4 axis:
1) becoming more compatible with MIT/GNU Scheme (e.g. normal/applicative order, control structures)
2) supporting more capabilities of the underlying Go implementation language (e.g. recent work supporting concurrency and channels)
3) our particular needs (e.g. byte array support)
4) useful additions (e.g. frames)

If GoLisp has a form or function that is also in MIT/GNU scheme, we strive to make it work the same way.

As much as possible the internals echo those in MIT/GNU Scheme. For example, the lexical environment structure/handling.

So, while it is intentionally very much like MIT/GNU Scheme, it is not constrained to follow the specification.  That said, unless our extensions are used, code will usually be indistinguishable. 

Dave
